# Generated by Django 5.2.8 on 2025-11-19 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partos', '0002_rename_semana_gestaciones_parto_semanas_gestacionales'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplicacionPostParto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PresentacionFetal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ReanimacionNeonatal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('basica', 'Básica'), ('avanzada', 'Avanzada')], default='basica', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='RecienNacido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('nombre_completo', models.CharField(blank=True, max_length=150)),
                ('peso', models.FloatField()),
                ('talla', models.FloatField()),
                ('apgar_1', models.PositiveSmallIntegerField()),
                ('apgar_5', models.PositiveSmallIntegerField()),
                ('codigo', models.CharField(max_length=20)),
                ('perimetro_cefalico', models.FloatField()),
                ('perimetro_toraxico', models.FloatField()),
                ('c_2480', models.PositiveSmallIntegerField()),
                ('destino_rn', models.CharField(max_length=40)),
                ('alojamiento_conjunto', models.BooleanField()),
                ('observaciones', models.TextField()),
                ('apego_canguro', models.BooleanField()),
                ('lactante_60', models.BooleanField()),
                ('apego_tunel', models.BooleanField()),
                ('gases_de_cordon', models.BooleanField()),
                ('complicaciones_postparto', models.ManyToManyField(related_name='rns', to='recien_nacidos.complicacionpostparto')),
                ('parto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rns', to='partos.parto')),
                ('presentacion_fetal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rns', to='recien_nacidos.presentacionfetal')),
                ('reanimaciones_neonatales', models.ManyToManyField(related_name='rns', to='recien_nacidos.reanimacionneonatal')),
            ],
        ),
        migrations.CreateModel(
            name='Vacunacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('reaccion_adversa', models.CharField(max_length=100)),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacunaciones', to='partos.profesional')),
                ('recien_nacido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacunaciones', to='recien_nacidos.reciennacido')),
            ],
        ),
    ]
