# Generated by Django 5.2.8 on 2025-12-06 22:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplicacionPostParto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PresentacionFetal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ReanimacionNeonatal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('basica', 'Básica'), ('avanzada', 'Avanzada')], default='basica', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TipoVacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecienNacido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_hora', models.DateTimeField()),
                ('nombre_completo_madre', models.CharField(blank=True, max_length=150)),
                ('peso', models.PositiveIntegerField()),
                ('talla', models.DecimalField(decimal_places=1, max_digits=4)),
                ('apgar_1', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('apgar_5', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('perimetro_cefalico', models.DecimalField(decimal_places=1, max_digits=4)),
                ('perimetro_toraxico', models.DecimalField(decimal_places=1, max_digits=4)),
                ('c_2480', models.PositiveSmallIntegerField()),
                ('destino_rn', models.CharField(max_length=40)),
                ('observaciones', models.TextField(blank=True)),
                ('alojamiento_conjunto', models.BooleanField()),
                ('apego_canguro', models.BooleanField()),
                ('lactante_60', models.BooleanField()),
                ('apego_tunel', models.BooleanField()),
                ('gases_de_cordon', models.BooleanField()),
                ('destino', models.CharField(choices=[('alojamiento', 'Alojamiento conjunto'), ('uci', 'UCI Neonatal'), ('uti', 'UTI Neonatal'), ('fallecido', 'Fallecido')], default='alojamiento', max_length=50)),
                ('complicaciones_postparto', models.ManyToManyField(related_name='rns', to='recien_nacidos.complicacionpostparto')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rns', to=settings.AUTH_USER_MODEL)),
                ('parto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rns', to='partos.parto')),
                ('presentacion_fetal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rns', to='recien_nacidos.presentacionfetal')),
                ('reanimaciones_neonatales', models.ManyToManyField(related_name='rns', to='recien_nacidos.reanimacionneonatal')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rns_actualizados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vacunacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('reaccion_adversa', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vacunaciones', to=settings.AUTH_USER_MODEL)),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacunaciones', to='partos.profesional')),
                ('recien_nacido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacunaciones', to='recien_nacidos.reciennacido')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacunas', to='recien_nacidos.tipovacuna')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vacunaciones_actualizacion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
