# Generated by Django 5.2.8 on 2025-12-06 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recien_nacidos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reciennacido',
            old_name='nombre_completo',
            new_name='nombre_completo_madre',
        ),
    ]
