# Generated by Django 5.2.8 on 2025-12-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recien_nacidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciennacido',
            name='sexo',
            field=models.CharField(choices=[('m', 'Masculino'), ('f', 'Femenino'), ('o', 'Otro')], default='o', max_length=10),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='destino_rn',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
