# Generated by Django 5.2.8 on 2025-12-03 02:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recien_nacidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoVacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='destino',
            field=models.CharField(choices=[('alojamiento', 'Alojamiento conjunto'), ('uci', 'UCI Neonatal'), ('uti', 'UTI Neonatal'), ('fallecido', 'Fallecido')], default='alojamiento', max_length=50),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='updated_by',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='apgar_1',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='apgar_5',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='codigo',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='perimetro_cefalico',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='perimetro_toraxico',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='peso',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='talla',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AddField(
            model_name='vacunacion',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='vacunas', to='recien_nacidos.tipovacuna'),
            preserve_default=False,
        ),
    ]
