# Generated by Django 5.2.8 on 2025-12-11 17:28

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partos', '0003_historicalparto'),
        ('recien_nacidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRecienNacido',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('fecha_hora', models.DateTimeField()),
                ('nombre_completo_madre', models.CharField(blank=True, max_length=150)),
                ('peso', models.PositiveIntegerField()),
                ('talla', models.DecimalField(decimal_places=1, max_digits=4)),
                ('apgar_1', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('apgar_5', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('codigo', models.CharField(db_index=True, max_length=20)),
                ('perimetro_cefalico', models.DecimalField(decimal_places=1, max_digits=4)),
                ('perimetro_toraxico', models.DecimalField(decimal_places=1, max_digits=4)),
                ('c_2480', models.PositiveSmallIntegerField()),
                ('destino_rn', models.CharField(blank=True, max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('alojamiento_conjunto', models.BooleanField()),
                ('apego_canguro', models.BooleanField()),
                ('lactante_60', models.BooleanField()),
                ('apego_tunel', models.BooleanField()),
                ('gases_de_cordon', models.BooleanField()),
                ('destino', models.CharField(choices=[('alojamiento', 'Alojamiento conjunto'), ('uci', 'UCI Neonatal'), ('uti', 'UTI Neonatal'), ('fallecido', 'Fallecido')], default='alojamiento', max_length=50)),
                ('sexo', models.CharField(choices=[('m', 'Masculino'), ('f', 'Femenino'), ('o', 'Otro')], default='o', max_length=10)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parto', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='partos.parto')),
                ('presentacion_fetal', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='recien_nacidos.presentacionfetal')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical recien nacido',
                'verbose_name_plural': 'historical recien nacidos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
