# Generated by Django 5.2.8 on 2025-12-13 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recien_nacidos', '0002_historicalreciennacido'),
        ('recien_nacidos', '0002_reciennacido_sexo_alter_reciennacido_destino_rn'),
    ]

    operations = [
    ]
