# Generated by Django 5.2.8 on 2025-11-18 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0003_gestacion_aborto_paciente_actividad_paciente_altura_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analgesia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=45)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Complicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GrupoRobson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('primer_apellido', models.CharField(max_length=45)),
                ('segundo_apellido', models.CharField(max_length=45)),
                ('rut', models.CharField(max_length=11)),
                ('tipo', models.CharField(choices=[('alumno', 'Alumno'), ('profesor', 'Profesor'), ('enfermera', 'Enfermera'), ('ayudante', 'Ayudante'), ('matrona', 'Matrona'), ('medico', 'Medico Obstetra'), ('anestesiologo', 'Anestesiologo'), ('pediatra', 'Pediatra o Neonatólogo')], default='enfermera', max_length=30)),
                ('telefono', models.CharField(max_length=45)),
                ('correo', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ViaNacimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=60)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Parto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('numero_aro', models.PositiveSmallIntegerField()),
                ('paridad', models.PositiveSmallIntegerField()),
                ('n_gestaciones', models.PositiveSmallIntegerField()),
                ('n_tactos_vaginales', models.PositiveSmallIntegerField()),
                ('rotura_membrana', models.CharField(choices=[('espontanea', 'Espontánea'), ('artificial', 'Artificial')], default='espontanea', max_length=50)),
                ('estado', models.CharField(choices=[('terminado', 'Terminado'), ('aborto', 'Aborto')], default='terminado', max_length=30)),
                ('estado_perine', models.CharField(choices=[('indemne', 'Indemne'), ('g1', 'Desgarro G1'), ('g2', 'Desgarro G2'), ('g3a', 'Desgarro G3 A'), ('g3b', 'Desgarro G3 B'), ('g3c', 'Desgarro G3 C'), ('g4', 'Desgarro G4'), ('fisura', 'Fisura'), ('episiotomia', 'Episiotomia')], default='indemne', max_length=30)),
                ('posicion', models.CharField(choices=[('semisentada', 'Semisentada'), ('sentada', 'Sentada'), ('litotomia', 'Litotomia'), ('dorsal', 'D.Dorsal'), ('cuadrupeda', 'Cuadrúpeda'), ('lateral', 'D.Lateral'), ('de pie', 'De Pie'), ('cuclillas', 'Cuclillas'), ('otro', 'Otro')], default='otro', max_length=50)),
                ('tiempo_membrana_rota', models.PositiveSmallIntegerField()),
                ('tiempo_dilatacion', models.PositiveSmallIntegerField()),
                ('tiempo_expulsivo', models.PositiveSmallIntegerField()),
                ('edad_madre', models.PositiveSmallIntegerField()),
                ('semana_gestaciones', models.PositiveSmallIntegerField()),
                ('monitor', models.BooleanField(default=False)),
                ('entrega_placenta', models.BooleanField(default=False)),
                ('acompaniante', models.BooleanField(default=False)),
                ('ttc', models.BooleanField(default=False)),
                ('induccion', models.BooleanField(default=False)),
                ('aceleracion', models.BooleanField(default=False)),
                ('oxitocina_profilactica', models.BooleanField(default=False)),
                ('uso_sala_saip', models.BooleanField(default=False)),
                ('esterilizacion', models.BooleanField(default=False)),
                ('analgesias', models.ManyToManyField(related_name='partos', to='partos.analgesia')),
                ('complicaciones', models.ManyToManyField(related_name='partos', to='partos.complicacion')),
                ('gestacion', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='parto', to='pacientes.gestacion')),
                ('grupo_robson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partos', to='partos.gruporobson')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partos', to=settings.AUTH_USER_MODEL)),
                ('profesionales', models.ManyToManyField(related_name='partos', to='partos.profesional')),
                ('tipo_de_ingreso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partos', to='partos.tipodeingreso')),
                ('via_nacimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partos', to='partos.vianacimiento')),
            ],
        ),
    ]
