# Generated by Django 5.2.8 on 2025-12-08 22:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parto',
            name='grupo_robson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partos', to='partos.gruporobson'),
        ),
        migrations.AlterField(
            model_name='parto',
            name='n_tactos_vaginales',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(40)]),
        ),
        migrations.AlterField(
            model_name='parto',
            name='numero_aro',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
