# Generated by Django 5.2.8 on 2025-11-18 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parto',
            old_name='semana_gestaciones',
            new_name='semanas_gestacionales',
        ),
    ]
