# Generated by Django 5.2.8 on 2025-12-03 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parto',
            name='grupo_robson',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='partos', to='partos.gruporobson'),
        ),
    ]
