# Generated by Django 5.2.8 on 2025-12-11 17:28

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_historicalgestacion'),
        ('partos', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalParto',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('hora_inicio', models.DateTimeField()),
                ('numero_aro', models.PositiveSmallIntegerField(default=0)),
                ('n_tactos_vaginales', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(40)])),
                ('rotura_membrana', models.CharField(choices=[('espontanea', 'Espontánea'), ('artificial', 'Artificial')], default='espontanea', max_length=50)),
                ('estado', models.CharField(choices=[('terminado', 'Terminado'), ('ingreso', 'Ingreso'), ('activo', 'Activo'), ('expulsivo', 'Expulsivo'), ('alumbramiento', 'Alumbramiento'), ('puerperio', 'Puerperio Inmediato')], default='ingreso', max_length=30)),
                ('posicion', models.CharField(choices=[('semisentada', 'Semisentada'), ('sentada', 'Sentada'), ('litotomia', 'Litotomia'), ('dorsal', 'D.Dorsal'), ('cuadrupeda', 'Cuadrúpeda'), ('lateral', 'D.Lateral'), ('de pie', 'De Pie'), ('cuclillas', 'Cuclillas'), ('otro', 'Otro')], default='otro', max_length=50)),
                ('tipo_regimen', models.CharField(choices=[('cero', 'Cero'), ('liquido', 'Liquido'), ('comun', 'Comun'), ('otro', 'Otro')], default='cero', max_length=50)),
                ('observaciones', models.TextField(blank=True, max_length=1000)),
                ('tiempo_membrana_rota', models.DurationField()),
                ('tiempo_dilatacion', models.DurationField()),
                ('tiempo_expulsivo', models.DurationField()),
                ('edad_madre', models.PositiveSmallIntegerField()),
                ('monitor', models.BooleanField(default=False)),
                ('entrega_placenta', models.BooleanField(default=False)),
                ('acompaniante', models.BooleanField(default=False)),
                ('ttc', models.BooleanField(default=False)),
                ('induccion', models.BooleanField(default=False)),
                ('aceleracion', models.BooleanField(default=False)),
                ('oxitocina_profilactica', models.BooleanField(default=False)),
                ('uso_sala_saip', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('gestacion', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pacientes.gestacion')),
                ('grupo_robson', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='partos.gruporobson')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tipo_de_ingreso', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='partos.tipodeingreso')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('via_nacimiento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='partos.vianacimiento')),
            ],
            options={
                'verbose_name': 'historical parto',
                'verbose_name_plural': 'historical partos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
