# Generated by Django 5.2.8 on 2025-12-03 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partos', '0002_rename_semana_gestaciones_parto_semanas_gestacionales'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAnalgesia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='parto',
            name='analgesias',
        ),
        migrations.RenameField(
            model_name='parto',
            old_name='fecha_ingreso',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='parto',
            name='estado_perine',
        ),
        migrations.RemoveField(
            model_name='parto',
            name='esterilizacion',
        ),
        migrations.RemoveField(
            model_name='parto',
            name='n_gestaciones',
        ),
        migrations.RemoveField(
            model_name='parto',
            name='paridad',
        ),
        migrations.RemoveField(
            model_name='parto',
            name='semanas_gestacionales',
        ),
        migrations.RemoveField(
            model_name='parto',
            name='usuario',
        ),
        migrations.AddField(
            model_name='parto',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parto',
            name='hora_inicio',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parto',
            name='observaciones',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='parto',
            name='tipo_regimen',
            field=models.CharField(choices=[('cero', 'Cero'), ('liquido', 'Liquido'), ('comun', 'Comun'), ('otro', 'Otro')], default='cero', max_length=50),
        ),
        migrations.AddField(
            model_name='parto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='parto',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partos_actualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profesional',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='complicacion',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='gruporobson',
            name='grupo',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='parto',
            name='estado',
            field=models.CharField(choices=[('terminado', 'Terminado'), ('ingreso', 'Ingreso'), ('activo', 'Activo'), ('expulsivo', 'Expulsivo'), ('alumbramiento', 'Alumbramiento'), ('puerperio', 'Puerperio Inmediato')], default='ingreso', max_length=30),
        ),
        migrations.AlterField(
            model_name='parto',
            name='tiempo_dilatacion',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='parto',
            name='tiempo_expulsivo',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='parto',
            name='tiempo_membrana_rota',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='rut',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='tipodeingreso',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='vianacimiento',
            name='tipo',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.CreateModel(
            name='Puerperio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_perine', models.CharField(choices=[('indemne', 'Indemne'), ('g1', 'Desgarro G1'), ('g2', 'Desgarro G2'), ('g3a', 'Desgarro G3 A'), ('g3b', 'Desgarro G3 B'), ('g3c', 'Desgarro G3 C'), ('g4', 'Desgarro G4'), ('fisura', 'Fisura'), ('episiotomia', 'Episiotomia')], default='indemne', max_length=30)),
                ('esterilizacion', models.BooleanField(default=False)),
                ('revision', models.BooleanField(default=False)),
                ('inercia_uterina', models.BooleanField(default=False)),
                ('restos_placenta', models.BooleanField(default=False)),
                ('trauma', models.BooleanField(default=False)),
                ('alteracion_coagulacion', models.BooleanField(default=False)),
                ('manejo_qirurgico_inercia_ut', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='puerperios', to=settings.AUTH_USER_MODEL)),
                ('parto', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='puerperio', to='partos.parto')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='puerperios_actualizados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnalgesiaParto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitada', models.BooleanField(default=False)),
                ('indicada', models.BooleanField(default=False)),
                ('administrada', models.BooleanField(default=False)),
                ('tiempo_espera_minutos', models.PositiveIntegerField(blank=True, help_text='Tiempo entre indicación y administración', null=True)),
                ('dosis', models.CharField(max_length=10)),
                ('notas', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analgesias', to=settings.AUTH_USER_MODEL)),
                ('parto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analgesias', to='partos.parto')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='partos.tipoanalgesia')),
            ],
        ),
        migrations.DeleteModel(
            name='Analgesia',
        ),
    ]
