# Generated by Django 5.2.8 on 2025-12-10 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partos', '0002_alter_parto_grupo_robson_and_more'),
        ('partos', '0002_initial'),
    ]

    operations = [
    ]
