# Generated by Django 5.2.8 on 2025-11-17 03:20

import apps.pacientes.fields.order_field
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('primer_apellido', models.CharField(max_length=100)),
                ('segundo_apellido', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=15)),
                ('nacionalidad', models.CharField(max_length=100)),
                ('comuna', models.CharField(max_length=59)),
                ('cesfam', models.CharField(max_length=50)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_nacimiento', models.DateField()),
                ('es_descapacitado', models.BooleanField(default=False)),
                ('es_pueblo_originario', models.BooleanField(default=False)),
                ('es_privada_de_libertad', models.BooleanField(default=False)),
                ('es_transexual', models.BooleanField(default=False)),
                ('plan_de_parto', models.BooleanField(default=False)),
                ('visita_guiada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gestacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana_gestacion', models.PositiveSmallIntegerField()),
                ('dias_gestacion', models.PositiveSmallIntegerField()),
                ('hipertension', models.BooleanField(default=False)),
                ('diabetes', models.BooleanField(default=False)),
                ('enfermedad_cardiaca', models.BooleanField(default=False)),
                ('multiple', models.BooleanField(default=False)),
                ('numero_fetos', models.BooleanField(default=False)),
                ('terminado', models.BooleanField(default=False)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('riezgo', models.CharField(choices=[('BAJO', 'Bajo Riesgo'), ('MEDIO', 'Riesgo Moderado'), ('ALTO', 'Alto Riesgo')], default='BAJO', max_length=10)),
                ('numero_gestacion', apps.pacientes.fields.order_field.OrderField()),
                ('matrona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gestaciones', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestaciones', to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='TestHepatitisB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(choices=[('positivo', 'Reactivo'), ('negativo', 'No Reactivo')], default='negativo', max_length=15)),
                ('fecha_toma', models.DateField()),
                ('durante_parto', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
                ('antibiotico', models.BooleanField(default=False)),
                ('orden', apps.pacientes.fields.order_field.OrderField()),
                ('derivacion_especialista', models.BooleanField(default=False)),
                ('gestacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='pacientes.gestacion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestSgb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(choices=[('positivo', 'Reactivo'), ('negativo', 'No Reactivo')], default='negativo', max_length=15)),
                ('fecha_toma', models.DateField()),
                ('durante_parto', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
                ('antibiotico', models.BooleanField(default=False)),
                ('orden', apps.pacientes.fields.order_field.OrderField()),
                ('gestacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='pacientes.gestacion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestVdrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(choices=[('positivo', 'Reactivo'), ('negativo', 'No Reactivo')], default='negativo', max_length=15)),
                ('fecha_toma', models.DateField()),
                ('durante_parto', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
                ('antibiotico', models.BooleanField(default=False)),
                ('orden', apps.pacientes.fields.order_field.OrderField()),
                ('gestacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='pacientes.gestacion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestVih',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(choices=[('positivo', 'Reactivo'), ('negativo', 'No Reactivo')], default='negativo', max_length=15)),
                ('fecha_toma', models.DateField()),
                ('durante_parto', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
                ('antibiotico', models.BooleanField(default=False)),
                ('orden', apps.pacientes.fields.order_field.OrderField()),
                ('n_aro', models.IntegerField()),
                ('en_preparto', models.BooleanField(default=False)),
                ('en_sala', models.BooleanField(default=False)),
                ('trimestre', models.CharField(choices=[('1', 'Primer Trimestre (0-12 semanas)'), ('2', 'Segundo Trimestre (13-27 semanas)'), ('3', 'Tercer Trimestre (28-40 semanas)')], default='1', max_length=20)),
                ('gestacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='pacientes.gestacion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='paciente',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paciente', to='pacientes.tipopaciente'),
        ),
    ]
