# Generated by Django 5.2.8 on 2025-11-17 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestacion',
            name='numero_fetos',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
