# Generated by Django 5.2.8 on 2025-12-10 19:52

import apps.pacientes.fields.order_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestacion',
            name='numero_gestacion',
            field=apps.pacientes.fields.order_field.OrderField(blank=True),
        ),
    ]
