# Generated by Django 5.2.8 on 2025-12-11 17:28

import apps.pacientes.fields.order_field
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalGestacion',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('numero_fetos', models.PositiveSmallIntegerField()),
                ('riesgo', models.CharField(choices=[('bajo', 'Bajo Riesgo'), ('medio', 'Riesgo Moderado'), ('alto', 'Alto Riesgo')], default='bajo', max_length=10)),
                ('estado', models.CharField(choices=[('terminada', 'Terminada'), ('aborto', 'Aborto'), ('curso', 'En Curso')], default='curso', max_length=10)),
                ('origen_datacion', models.CharField(choices=[('fur', 'FUR'), ('eco', 'ECO'), ('sin', 'Sin Datacion Disponible')], default='sin', help_text='La fecha de inicio de gestación se tomará según el origen que seleccione: FUR o ECO.', max_length=3)),
                ('fur', models.DateField(blank=True, null=True)),
                ('fecha_eco', models.DateField(blank=True, null=True)),
                ('semanas_eco', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('dias_eco', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fecha_inicio_gestacion', models.DateField(blank=True, null=True)),
                ('numero_gestacion', apps.pacientes.fields.order_field.OrderField(blank=True)),
                ('enfermedad_cardiaca', models.BooleanField(default=False)),
                ('hipertension', models.BooleanField(default=False)),
                ('diabetes', models.BooleanField(default=False)),
                ('multiple', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pacientes.paciente')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Gestacion',
                'verbose_name_plural': 'historical Gestaciones',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
