# Generated by Django 5.2.8 on 2025-12-10 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_alter_gestacion_numero_gestacion'),
        ('pacientes', '0002_initial'),
    ]

    operations = [
    ]
