# Generated by Django 5.2.8 on 2025-12-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_alter_paciente_identificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
    ]
