# Generated by Django 5.2.8 on 2025-11-18 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_alter_gestacion_numero_fetos'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestacion',
            name='aborto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paciente',
            name='actividad',
            field=models.CharField(choices=[('baja', 'Baja'), ('moderada', 'Moderada'), ('alta', 'Alta')], default='baja', max_length=9),
        ),
        migrations.AddField(
            model_name='paciente',
            name='altura',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='peso',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
