# Generated by Django 5.2.8 on 2025-11-19 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_gestacion_aborto_paciente_actividad_paciente_altura_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gestacion',
            options={'verbose_name': 'Gestacion', 'verbose_name_plural': 'Gestaciones'},
        ),
    ]
