# Generated by Django 5.2.8 on 2025-12-13 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_historicalgestacion'),
        ('pacientes', '0003_merge_20251210_1909'),
    ]

    operations = [
    ]
