# Generated by Django 5.2.8 on 2025-11-21 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_alter_gestacion_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cesfam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'ordering': ['comuna__nombre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='paciente',
            name='rut',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cesfam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paciente', to='pacientes.cesfam'),
        ),
        migrations.AddField(
            model_name='cesfam',
            name='comuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pacientes.comuna'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='comuna',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paciente', to='pacientes.comuna'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nacionalidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paciente', to='pacientes.nacionalidad'),
        ),
    ]
