# Generated by Django 5.2.8 on 2025-11-21 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_cesfam_comuna_nacionalidad_alter_paciente_rut_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='rut',
            new_name='identificacion',
        ),
        migrations.AddField(
            model_name='paciente',
            name='documento',
            field=models.CharField(choices=[('RUT', 'Rut'), ('PAS', 'Pasaporte'), ('EXT', 'Documento extranjero'), ('TMP', 'Sin documento / Temporal')], default='RUT', max_length=3),
        ),
    ]
