# Generated by Django 5.2.8 on 2025-11-21 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0006_rename_rut_paciente_identificacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='es_descapacitado',
            new_name='descapacitado',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='es_privada_de_libertad',
            new_name='privada_de_libertad',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='es_pueblo_originario',
            new_name='pueblo_originario',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='es_transexual',
            new_name='transexual',
        ),
    ]
