# Generated by Django 5.2.8 on 2025-11-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0007_rename_es_descapacitado_paciente_descapacitado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='direccion',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='paciente',
            unique_together={('documento', 'identificacion')},
        ),
    ]
