# Generated by Django 5.2.8 on 2025-12-03 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0009_paciente_telefono_alter_paciente_identificacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='gestacion',
            old_name='fecha_ingreso',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='gestacion',
            old_name='fecha_actualizacion',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='fecha_ingreso',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='gestacion',
            name='aborto',
        ),
        migrations.RemoveField(
            model_name='gestacion',
            name='dias_gestacion',
        ),
        migrations.RemoveField(
            model_name='gestacion',
            name='matrona',
        ),
        migrations.RemoveField(
            model_name='gestacion',
            name='riezgo',
        ),
        migrations.RemoveField(
            model_name='gestacion',
            name='semana_gestacion',
        ),
        migrations.RemoveField(
            model_name='gestacion',
            name='terminado',
        ),
        migrations.RemoveField(
            model_name='testvih',
            name='en_preparto',
        ),
        migrations.RemoveField(
            model_name='testvih',
            name='en_sala',
        ),
        migrations.AddField(
            model_name='gestacion',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gestaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gestacion',
            name='dias_eco',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gestacion',
            name='estado',
            field=models.CharField(choices=[('terminada', 'Terminada'), ('aborto', 'Aborto'), ('curso', 'En Curso')], default='curso', max_length=10),
        ),
        migrations.AddField(
            model_name='gestacion',
            name='fecha_eco',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gestacion',
            name='fecha_inicio_gestacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gestacion',
            name='fur',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gestacion',
            name='origen_datacion',
            field=models.CharField(blank=True, choices=[('fur', 'FUR'), ('eco', 'ECO')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='gestacion',
            name='riesgo',
            field=models.CharField(choices=[('bajo', 'Bajo Riesgo'), ('medio', 'Riesgo Moderado'), ('alto', 'Alto Riesgo')], default='bajo', max_length=10),
        ),
        migrations.AddField(
            model_name='gestacion',
            name='semanas_eco',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gestacion',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gestaciones_actualizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paciente',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pacientes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paciente',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pacientes_actualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testhepatitisb',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='testhepatitisb',
            name='lugar_toma',
            field=models.CharField(choices=[('preparto', 'Preparto'), ('sala_parto', 'Sala de Partos'), ('urgencia', 'Urgencias')], default='preparto', max_length=12),
        ),
        migrations.AddField(
            model_name='testsgb',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='testsgb',
            name='lugar_toma',
            field=models.CharField(choices=[('preparto', 'Preparto'), ('sala_parto', 'Sala de Partos'), ('urgencia', 'Urgencias')], default='preparto', max_length=12),
        ),
        migrations.AddField(
            model_name='testvdrl',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='testvdrl',
            name='lugar_toma',
            field=models.CharField(choices=[('preparto', 'Preparto'), ('sala_parto', 'Sala de Partos'), ('urgencia', 'Urgencias')], default='preparto', max_length=12),
        ),
        migrations.AddField(
            model_name='testvih',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='testvih',
            name='lugar_toma',
            field=models.CharField(choices=[('preparto', 'Preparto'), ('sala_parto', 'Sala de Partos'), ('urgencia', 'Urgencias')], default='preparto', max_length=12),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='altura',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cesfam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paciente', to='pacientes.cesfam'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='comuna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paciente', to='pacientes.comuna'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='direccion',
            field=models.CharField(blank=True, default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='testhepatitisb',
            name='fecha_toma',
            field=models.DateField(help_text='Fecha en la que se toma el examen'),
        ),
        migrations.AlterField(
            model_name='testhepatitisb',
            name='observaciones',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='testsgb',
            name='fecha_toma',
            field=models.DateField(help_text='Fecha en la que se toma el examen'),
        ),
        migrations.AlterField(
            model_name='testsgb',
            name='observaciones',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='testvdrl',
            name='fecha_toma',
            field=models.DateField(help_text='Fecha en la que se toma el examen'),
        ),
        migrations.AlterField(
            model_name='testvdrl',
            name='observaciones',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='testvih',
            name='fecha_toma',
            field=models.DateField(help_text='Fecha en la que se toma el examen'),
        ),
        migrations.AlterField(
            model_name='testvih',
            name='n_aro',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='testvih',
            name='observaciones',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['documento', 'identificacion'], name='pacientes_p_documen_5ec0fa_idx'),
        ),
    ]
