from .parto_views import ListarPartosView, CrearPartosView, AutoCompletadoParaGestacion, MenuInicioPartosView, ActualizarPartoView, EliminarPartoView, DetallesPartoView
from .puerperio_views import CreatePuerperioView
from .wizard_form_view import WizardFormView