# Generated by Django 5.2.8 on 2025-11-16 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matronaperfil',
            name='fecha_contratacion',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='matronaperfil',
            name='foto_perfil',
            field=models.FileField(blank=True, upload_to='imagen_perfil'),
        ),
        migrations.AlterField(
            model_name='matronaperfil',
            name='rut',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='matronaperfil',
            name='telefono',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='supervisorperfil',
            name='fecha_contratacion',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='supervisorperfil',
            name='foto_perfil',
            field=models.FileField(blank=True, upload_to='imagen_perfil'),
        ),
        migrations.AlterField(
            model_name='supervisorperfil',
            name='rut',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='supervisorperfil',
            name='telefono',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
