# Generated by Django 5.2.8 on 2025-11-17 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0002_alter_matronaperfil_fecha_contratacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matronaperfil',
            options={'verbose_name': 'Perfil Matrona', 'verbose_name_plural': 'Perfiles Matronas'},
        ),
        migrations.AlterModelOptions(
            name='supervisorperfil',
            options={'verbose_name': 'Perfiles Supervisores'},
        ),
    ]
