# Generated by Django 5.2.8 on 2025-11-18 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0003_alter_matronaperfil_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matronaperfil',
            name='foto_perfil',
            field=models.FileField(blank=True, upload_to='imagen_perfil/'),
        ),
        migrations.AlterField(
            model_name='supervisorperfil',
            name='foto_perfil',
            field=models.FileField(blank=True, upload_to='imagen_perfil/'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='tipo',
            field=models.CharField(choices=[('diurno', 'Diurno'), ('vespertino', 'Vespertino')], default='diurno', max_length=30),
        ),
    ]
