# Generated by Django 5.2.8 on 2025-11-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0004_alter_matronaperfil_foto_perfil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='first_login',
            field=models.BooleanField(default=True),
        ),
    ]
