# Generated by Django 5.2.8 on 2025-12-01 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0005_usuario_first_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoVerificacionEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(max_length=6)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('expired_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_email', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
