# Generated by Django 5.2.8 on 2025-12-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0006_codigoverificacionemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigoverificacionemail',
            name='code',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
