# Generated by Django 5.2.8 on 2025-12-01 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0007_alter_codigoverificacionemail_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigoverificacionemail',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_email', to=settings.AUTH_USER_MODEL),
        ),
    ]
